version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: d_payment_gateway_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
      - PAYMENT_API_URL=https://payment1.spmode.ne.jp/api/fes/rksrv/testsrvresource
      - PAYMENT_COMPANY_CODE=DCM12345678
      - PAYMENT_STORE_CODE=TNP00000001
      - PAYMENT_AUTHENTICATION_PASS=XXXXXXXXXXXXXXXXXXXX
      - BACKEND_CORS_ORIGINS=["http://localhost:8000", "http://localhost:3000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s